[versions]
org-jetbrains-kotlin = "1.9.22"
android-gradle-plugin = "8.1.1"

[libraries]
# Dependencies of the included build-logic
android-tools-build = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }

[plugins]
easy-android-test = { id = "org.easy.android.test" }
easy-application = { id = "org.easy.android.application" }
easy-compose-application = { id = "org.easy.android.application.compose" }
easy-library = { id = "org.easy.android.library" }
easy-compose-library = { id = "org.easy.android.library.compose" }
easy-hilt = { id = "org.easy.hilt"}
easy-jacoco = { id = "org.easy.jacoco" }
easy-koin = { id = "org.easy.koin" }
easy-multiplatform = { id = "org.easy.multiplatform" }