[versions]
androidx-core-splashscreen = "1.0.1"
androidx-core-ktx = "1.10.1"
androidx-appcompat = "1.6.1"
androidx-paging = "3.2.0"

[libraries]
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "androidx-paging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging" }
